# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('fans_amount', models.BigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BandAtEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_.Band')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('min_age', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('url', models.URLField()),
                ('presenting_bands', models.ManyToManyField(through='api_.BandAtEvent', to='api_.Band')),
            ],
        ),
        migrations.CreateModel(
            name='Fa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=255, null=True)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaAtEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.CharField(choices=[('m', 'maybe'), ('i', 'interested'), ('n', 'nah'), ('g', 'going')], max_length=1, null=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'bad'), (2, 'meh'), (3, 'nice'), (4, 'awesome'), (5, 'loved it')], null=True)),
                ('comment', models.TextField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_.Event')),
                ('fa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_.Fa')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('max_capacity', models.BigIntegerField()),
                ('events', models.ManyToManyField(to='api_.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MusicGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('parent_genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_.MusicGenre')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('formatted_address', models.CharField(max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=6, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('band_confirmed', models.NullBooleanField(default=None)),
                ('host_confirmed', models.NullBooleanField(default=None)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_.Band')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_.Event')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_.Host')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_.Place'),
        ),
        migrations.AddField(
            model_name='host',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fa',
            name='events',
            field=models.ManyToManyField(through='api_.FaAtEvent', to='api_.Event'),
        ),
        migrations.AddField(
            model_name='fa',
            name='favorite_genres',
            field=models.ManyToManyField(to='api_.MusicGenre'),
        ),
        migrations.AddField(
            model_name='fa',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_.Place'),
        ),
        migrations.AddField(
            model_name='fa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bandatevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_.Event'),
        ),
        migrations.AddField(
            model_name='band',
            name='events',
            field=models.ManyToManyField(through='api_.BandAtEvent', to='api_.Event'),
        ),
        migrations.AddField(
            model_name='band',
            name='genres',
            field=models.ManyToManyField(to='api_.MusicGenre'),
        ),
        migrations.AddField(
            model_name='band',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_.Place'),
        ),
        migrations.AddField(
            model_name='band',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
