# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('genre', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('fans_amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('starts_at', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('ends_at', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('url', models.URLField()),
                ('max_capacity', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(default='', max_length=255, unique=True)),
                ('zip_code', models.CharField(max_length=25)),
                ('street', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'fa'), (2, 'band'), (3, 'recorder'), (4, 'venue')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api_.Location')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='location',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api_.Location'),
        ),
        migrations.AddField(
            model_name='host',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api_.Host'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api_.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='presenting',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api_.Band'),
        ),
        migrations.AddField(
            model_name='band',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_.User'),
        ),
    ]
