# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicgenre',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='bandatevent',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='bandatevent',
            name='starts_at',
        ),
        migrations.RemoveField(
            model_name='host',
            name='events',
        ),
        migrations.RemoveField(
            model_name='musicgenre',
            name='parent_genre',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='band_confirmed',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='host',
        ),
        migrations.AddField(
            model_name='bandatevent',
            name='proposition',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api_.Proposition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_event', to='api_.Host'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='faatevent',
            name='feeling',
            field=models.CharField(choices=[('i', 'interested'), ('n', 'nah'), ('g', 'going')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api_.Event'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('name', 'starts_at')]),
        ),
    ]
