# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
