# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_', '0002_auto_20170823_2011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaAtEvent',
            new_name='EventPublic',
        ),
        migrations.RemoveField(
            model_name='bandatevent',
            name='band',
        ),
        migrations.RemoveField(
            model_name='bandatevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='bandatevent',
            name='proposition',
        ),
        migrations.AlterModelOptions(
            name='eventpublic',
            options={'verbose_name_plural': 'EventsPublic'},
        ),
        migrations.RenameField(
            model_name='band',
            old_name='fans_amount',
            new_name='fas_amount',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='genres',
            new_name='music_genres',
        ),
        migrations.RenameField(
            model_name='fa',
            old_name='favorite_genres',
            new_name='music_genres',
        ),
        migrations.RemoveField(
            model_name='band',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api_.Band'),
        ),
        migrations.AddField(
            model_name='event',
            name='music_genres',
            field=models.ManyToManyField(to='api_.MusicGenre'),
        ),
        migrations.AddField(
            model_name='event',
            name='public',
            field=models.ManyToManyField(through='api_.EventPublic', to='api_.Fa'),
        ),
        migrations.AddField(
            model_name='host',
            name='music_genres',
            field=models.ManyToManyField(to='api_.MusicGenre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api_.Host'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='api_.Band'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='api_.Event'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='presenting_bands',
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('name', 'host', 'starts_at')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventpublic',
            unique_together=set([('fa', 'event')]),
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='starts_at',
        ),
        migrations.AlterUniqueTogether(
            name='proposition',
            unique_together=set([('band', 'event')]),
        ),
        migrations.DeleteModel(
            name='BandAtEvent',
        ),
    ]
