# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_', '0002_auto_20170702_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='presenting',
        ),
        migrations.RemoveField(
            model_name='location',
            name='place',
        ),
        migrations.AddField(
            model_name='location',
            name='place_id',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, default='', max_length=254, unique=True),
        ),
    ]
