# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_', '0003_auto_20170829_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpublic',
            options={'verbose_name_plural': "Event's Public"},
        ),
        migrations.AlterModelOptions(
            name='musicgenre',
            options={'ordering': ['name'], 'verbose_name_plural': 'Music Genres'},
        ),
        migrations.AddField(
            model_name='proposition',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='api_.Host'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='proposition',
            unique_together=set([('band', 'event'), ('host', 'event')]),
        ),
    ]
