# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_', '0003_auto_20170703_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('f', 'fa'), ('b', 'band'), ('r', 'recorder'), ('h', 'host')], max_length=10),
        ),
    ]
