# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_', '0004_auto_20170830_2055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposition',
            unique_together=set([('band', 'event')]),
        ),
    ]
