# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_', '0005_auto_20170830_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='fas_amount',
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
