# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_', '0006_auto_20170904_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition',
            old_name='host_confirmed',
            new_name='confirmed',
        ),
    ]
